import Lean
import KLR.BIR.Instruction

-- This file is automatically generated by brewer
namespace KLR.BIR

inductive ActivationFunctionType where
  | Identity
  | Square
  | Relu
  | Lrelu
  | Prelu
  | Sigmoid
  | Tanh
  | Exp
  | Softplus
  | Sqrt
  | Rsqrt
  | Dsqrt
  | Ln
  | Ln_prime
  | Erf
  | Sin
  | Arctan
  | Sign
  | Gelu
  | Mish
  | Gelu_apprx_tanh
  | Gelu_apprx_sigmoid
  | Derivative_Gelu
  | Derivative_Erf
  | Copy
  | Abs
  | Reciprocal
  | Abs_reciprocal_sqrt
  | MemsetZero
  | Silu
  | Derivative_silu
  | Is_finite
  | Unknown
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

inductive EngineAccumulationType where
  | Idle
  | Zero
  | Accumulate
  | ZeroAccumulate
  | AddAccumulate
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

inductive MatmultPerfMode where
  | None
  | DoubleRow
  | DoubleColumn
  | DoublePixel
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

inductive MemsetMode where
  | Const
  | Random
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

inductive DGEType where
  | None
  | SWDGE
  | HWDGE
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

inductive PoolFunctionType where
  | Max
  | Avg
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

inductive AluOpType where
  | bypass
  | bitwise_not
  | arith_shift_left
  | arith_shift_right
  | add
  | subtract
  | mult
  | divide
  | max
  | min
  | bitwise_and
  | bitwise_or
  | bitwise_xor
  | logical_and
  | logical_or
  | logical_xor
  | logical_shift_left
  | logical_shift_right
  | is_equal
  | not_equal
  | is_gt
  | is_ge
  | is_lt
  | is_le
  | average
  | elemwise_mul
  | pow
  | mod
  | rsqrt
  | abs
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

inductive AxisListType where
  | X
  | XY
  | XYZ
  | XYZW
  | XYZWC
  | C
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

inductive CopyMode where
  | Copy
  | Transpose
  | CCE
  | Replicate
  | Dynamic
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

inductive TransposeOps where
  | None
  | WZXY
  | WXZY
  | WYXZ
  | ZWYX
  | ZYWX
  | ZYXW
  | YXWZ
  | YXZW
  | YWZX
  | XWZY
  | XZYW
  | XYWZ
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

inductive CollectiveKind where
  | SendRecv
  | SendRecvCCE
  | AllReduce
  | ReduceScatter
  | AllGather
  | AllToAll
  | Permute
  | PermuteReduce
  | PermuteImplicit
  | PermuteReduceImplicit
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

inductive CollectiveComputeTypeHint where
  | TP
  | FSDP
  | None
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

inductive RandomAlgorithmKind where
  | LFSR
  | PCG32
  | PHILOX_1
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

inductive RandomDistributionKind where
  | Raw
  | Uniform
  | Normal
  | Binomial
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

inductive BranchCompareOp where
  | IS_LTIMM
  | IS_LEIMM
  | IS_EQIMM
  | IS_NEIMM
  | IS_GEIMM
  | IS_GTIMM
  | IS_LTREG
  | IS_LEREG
  | IS_EQREG
  | IS_NEREG
  | IS_GEREG
  | IS_GTREG
  | Unsupported
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

-- Instruction

structure Activation extends Instruction where
  opcode := "Activation"
  scale : Option Float := some 0
  alpha : Option Float := some 0
  can_read_uninit : Option Bool := some False
  func : ActivationFunctionType
  acc : Option EngineAccumulationType := some .Idle
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure ReadActivationAccumulator extends Instruction where
  opcode := "ReadActivationAccumulator"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure LoadActFuncSet extends Instruction where
  opcode := "LoadActFuncSet"
  act_func_set_id : Option Int := none
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure Memset extends Instruction where
  opcode := "Memset"
  mode : MemsetMode
  constant : Nat
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure GetGlobalRankId extends Instruction where
  opcode := "GetGlobalRankId"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure NoOp extends Instruction where
  opcode := "NoOp"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure EventSemaphore extends Instruction where
  opcode := "EventSemaphore"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure AllEngineBarrier extends Instruction where
  opcode := "AllEngineBarrier"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure Drain extends Instruction where
  opcode := "Drain"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure Halt extends Instruction where
  opcode := "Halt"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure Pool extends Instruction where
  opcode := "Pool"
  func : PoolFunctionType
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure Reciprocal extends Instruction where
  opcode := "Reciprocal"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure Shuffle extends Instruction where
  opcode := "Shuffle"
  indices : List Nat
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure TensorCopy extends Instruction where
  opcode := "TensorCopy"
  can_read_uninit : Option Bool := some False
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure TensorCopyDynamicSrc extends Instruction where
  opcode := "TensorCopyDynamicSrc"
  scale : Option Nat := none
  can_read_uninit : Option Bool := some False
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure TensorCopyDynamicDst extends Instruction where
  opcode := "TensorCopyDynamicDst"
  scale : Option Nat := none
  can_read_uninit : Option Bool := some False
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure IndirectCopy extends Instruction where
  opcode := "IndirectCopy"
  num_valid_indices : Nat
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure TensorReduce extends Instruction where
  opcode := "TensorReduce"
  op : AluOpType
  axis : AxisListType
  apply_transpose : Option Bool := some False
  negate : Option Bool := some False
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure TensorScalar extends Instruction where
  opcode := "TensorScalar"
  op0 : AluOpType
  const0 : Float
  reverse0 : Bool
  op1 : AluOpType
  const1 : Float
  reverse1 : Bool
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure TensorScalarPtr extends Instruction where
  opcode := "TensorScalarPtr"
  op0 : AluOpType
  reverse0 : Bool
  op1 : AluOpType
  reverse1 : Bool
  apply_transpose : Option Bool := some False
  is_tensor_scalar_addr : Option Bool := some False
  is_scalar_tensor_tensor : Option Bool := some False
  is_tensor_tensor_scan : Option Bool := some False
  acc : Option EngineAccumulationType := some .Idle
  negate_second_output : Option Bool := some False
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure TensorTensor extends Instruction where
  opcode := "TensorTensor"
  op : AluOpType
  acc : Option EngineAccumulationType := some .Idle
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure BNStats extends Instruction where
  opcode := "BNStats"
  apply_transpose : Option Bool := some False
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure BNStatsAggregate extends Instruction where
  opcode := "BNStatsAggregate"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure BNGradients extends Instruction where
  opcode := "BNGradients"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure BNBackprop extends Instruction where
  opcode := "BNBackprop"
  total_elements : Float
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure BNBackprop2 extends Instruction where
  opcode := "BNBackprop2"
  total_elements : Float
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure StreamShuffle extends Instruction where
  opcode := "StreamShuffle"
  mask : List Nat
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure CalcVarAddr extends Instruction where
  opcode := "CalcVarAddr"
  baseoffset : Nat
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure StreamTranspose extends Instruction where
  opcode := "StreamTranspose"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure Select extends Instruction where
  opcode := "Select"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure CopyPredicated extends Instruction where
  opcode := "CopyPredicated"
  can_read_uninit : Option Bool := some False
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure CustomOp extends Instruction where
  opcode := "CustomOp"
  opFunctionName : String
  opLibFile : String
  ulib_to_ucode_version : String
  ulib_to_isa_version : String
  is_builtin : Option Bool := some False
  srcsShape : List ShapeVector
  dstsShape : List ShapeVector
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure BIRKernel extends Instruction where
  opcode := "BIRKernel"
  kernel_name : String
  srcs_shape : List ShapeVector
  dsts_shape : List ShapeVector
  kernel_attrs : List (String × String)
  sb_buf_shape : Nat × Nat
  psum_buf_shape : Nat × Nat × Nat
  auto_cast : String
  auto_cast_type : String
  is_causal : Option Bool := some False
  fused_rmsnorm : Option Bool := some True
  norm_type : Option Int := none
  lnc_size : Option Int := none
  lower_bound : Option Float := some 0
  store_add : Option Bool := some False
  quant_kernel : Option Bool := some False
  output_layout : Option Int := some 0
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure NKIKernel extends Instruction where
  opcode := "NKIKernel"
  func : String
  sb_buf_shape : Nat × Nat
  psum_buf_shape : Nat × Nat × Nat
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure GetRandState extends Instruction where
  opcode := "GetRandState"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure SetRandState extends Instruction where
  opcode := "SetRandState"
  rng_engine : EngineType
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure Rand extends Instruction where
  opcode := "Rand"
  random_algorithm : RandomAlgorithmKind
  rand_num_steps : Nat
  distribution : RandomDistributionKind
  params : List Float
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure Iota extends Instruction where
  opcode := "Iota"
  base : Option Int := some 0
  pattern : List APPair
  channel_multiplier : Option Int := some 0
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure TensorScalarAffineSelect extends Instruction where
  opcode := "TensorScalarAffineSelect"
  base : Option Int := some 0
  pattern : List APPair
  channel_multiplier : Option Int := some 0
  compare_op : AluOpType
  fill_value : Option Float := some 0
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure Dropout extends Instruction where
  opcode := "Dropout"
  is_keep_threshold : Option Bool := some False
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure GetCurProcessingRankID extends Instruction where
  opcode := "GetCurProcessingRankID"
  iter_id : Nat
  channel_id : Nat
  stream_id : Option Int := some 0
  replica_groups : Option (List (List Nat)) := none
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure RegisterAlu extends Instruction where
  opcode := "RegisterAlu"
  op : AluOpType
  is_64bit : Option Bool := some False
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure RegisterMove extends Instruction where
  opcode := "RegisterMove"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure TensorLoad extends Instruction where
  opcode := "TensorLoad"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure TensorSave extends Instruction where
  opcode := "TensorSave"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure Call extends Instruction where
  opcode := "Call"
  target : Option String := none
  table_id : Option Int := none
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure SwitchQueueInstance extends Instruction where
  opcode := "SwitchQueueInstance"
  queue : Option String := none
  instance_name : Option String := none
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure CoreBarrier extends Instruction where
  opcode := "CoreBarrier"
  runtime_semaphore : Option Nat := some 0
  id : Nat
  cores : List Nat
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure Max extends Instruction where
  opcode := "Max"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure MaxIndex extends Instruction where
  opcode := "MaxIndex"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure MatchReplace extends Instruction where
  opcode := "MatchReplace"
  imm_value : Float
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure Gather extends Instruction where
  opcode := "Gather"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure InlineASMBytes extends Instruction where
  opcode := "InlineASMBytes"
  asm_bytes : String
  sync_type : InstSyncType
  latency_estimate : Int
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

-- Generic

structure Generic extends Instruction where
  opcode := "Generic"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure GenericCopy extends Generic where
  opcode := "GenericCopy"
  can_read_uninit : Option Bool := some False
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure GenericRelu extends Generic where
  opcode := "GenericRelu"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure AbstractCopy extends Generic where
  opcode := "AbstractCopy"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

-- MatmultBase

structure MatmultBase extends Instruction where
  opcode := "MatmultBase"
  start_tensor_calc : Bool
  stop_tensor_calc : Option Bool := some False
  replication_resolution : Option Nat := some 0
  replication_shift_amnt : Option Nat := some 0
  replication_num_rows : Option Nat := some 0
  is_transpose : Option Bool := some False
  is_fmap_onezero : Option Bool := some False
  is_weight_onezero : Option Bool := some False
  tile_size : Option (Nat × Nat) := some (0, 0)
  tile_position : Option (List (Nat × Nat)) := some [(0,0)]
  perf_mode : Option MatmultPerfMode := some .None
  ifmap_quant_offset : Option Nat := some 0
  weights_quant_offset : Option Nat := some 0
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure Matmult extends MatmultBase where
  opcode := "Matmult"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure MatmultSparse extends MatmultBase where
  opcode := "MatmultSparse"
  compress_ratio : Int
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

-- DMA

structure DMA extends Instruction where
  opcode := "DMA"
  queue : Option String := none
  dge_type : Option DGEType := some .None
  duplicate : Option Bool := some False
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure Load extends DMA where
  opcode := "Load"
  can_read_uninit : Option Bool := some False
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure Save extends DMA where
  opcode := "Save"
  can_read_uninit : Option Bool := some False
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure DMACopy extends DMA where
  opcode := "DMACopy"
  mode : CopyMode
  oob_is_err : Option Bool := some True
  transpose_op : Option TransposeOps := some .None
  constants : Option (List Float) := none
  cce_op : Option AluOpType := some .bypass
  replica_groups : Option (List (List Nat)) := none
  remote_notification : Option (List Nat) := some []
  can_read_uninit : Option Bool := some False
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure ReadVarAddr extends DMA where
  opcode := "ReadVarAddr"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure GenericIndirectLoad extends DMA where
  opcode := "GenericIndirectLoad"
  indirect_dims : Option (List Nat) := some []
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure IndirectLoad extends DMA where
  opcode := "IndirectLoad"
  runtime_semaphore_wait_value : Option Nat := some 0
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure GenericIndirectSave extends DMA where
  opcode := "GenericIndirectSave"
  indirect_dims : Option (List Nat) := some []
  op : Option AluOpType := some .add
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure IndirectSave extends DMA where
  opcode := "IndirectSave"
  runtime_semaphore_wait_value : Option Nat := some 0
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure IndirectSaveAccumulate extends DMA where
  opcode := "IndirectSaveAccumulate"
  num_indices : Nat
  entry_step_elements : Nat
  op : Option AluOpType := some .add
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure DMATrigger extends DMA where
  opcode := "DMATrigger"
  dma_blocks : Option String := none
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

-- Collective

structure Collective extends Instruction where
  opcode := "Collective"
  queue : Option String := none
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure CollectiveCompute extends Collective where
  opcode := "CollectiveCompute"
  kind : Option CollectiveKind := some .AllReduce
  replica_groups : Option (List (List Nat)) := none
  cc_channel : Option Index := none
  stream_id : Option Int := some 0
  src_target_pairs : Option (List (List Nat)) := none
  op : Option AluOpType := some .bypass
  can_read_uninit : Option Bool := some False
  is_local : Option Bool := some False
  pipe_id : Option Nat := some 0
  recv_from_rank : Option (List Index) := some []
  send_to_rank : Option Index := none
  initial_corebarrier : Option Bool := some True
  cc_type_hint : Option CollectiveComputeTypeHint := some .None
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure CollectiveSend extends Collective where
  opcode := "CollectiveSend"
  peer_id : Nat
  can_read_uninit : Option Bool := some False
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure CollectiveRecv extends Collective where
  opcode := "CollectiveRecv"
  peer_id : Nat
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

-- DMADescriptor

structure DMADescriptor extends Instruction where
  opcode := "DMADescriptor"
  num_tiling_dimensions : Option Nat := some 0
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure DMADescriptorCopy extends DMADescriptor where
  opcode := "DMADescriptorCopy"
  can_read_uninit : Option Bool := some False
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure DMADescriptorCCE extends DMADescriptor where
  opcode := "DMADescriptorCCE"
  constants : List Float
  op : AluOpType
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure DMADescriptorTranspose extends DMADescriptor where
  opcode := "DMADescriptorTranspose"
  transpose_op : TransposeOps
  can_read_uninit : Option Bool := some False
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure DMADescriptorReplicate extends DMADescriptor where
  opcode := "DMADescriptorReplicate"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

-- Terminator

structure Terminator extends Instruction where
  opcode := "Terminator"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure CompareAndBranch extends Terminator where
  opcode := "CompareAndBranch"
  comp_op : BranchCompareOp
  on_true : Option String := none
  on_false : Option String := none
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure UnconditionalBranch extends Terminator where
  opcode := "UnconditionalBranch"
  target : Option String := none
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure Return extends Terminator where
  opcode := "Return"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure Break extends Terminator where
  opcode := "Break"
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

-- Symbolic

structure MatmultSymbolic extends Instruction where
  opcode := "MatmultSymbolic"
  replication_resolution : Nat
  replication_shift_amnt : Nat
  replication_num_rows : Nat
  start_tensor_calc : Bool
  stop_tensor_calc : Option Bool := some False
  is_transpose : Option Bool := some False
  rowgrp_symbolic : Index
  colgrp_symbolic : Index
  is_fmap_onezero : Option Bool := some False
  is_weight_onezero : Option Bool := some False
  tile_position : Option (List (Nat × Nat)) := some [(0,0)]
  perf_mode : Option MatmultPerfMode := some .None
  ifmap_quant_offset : Option Nat := some 0
  weights_quant_offset : Option Nat := some 0
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure ShuffleSymbolic extends Instruction where
  opcode := "ShuffleSymbolic"
  elts : List Nat
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure TensorScalarSymbolic extends Instruction where
  opcode := "TensorScalarSymbolic"
  op0 : AluOpType
  value0 : List Float
  expr0 : Index
  reverse0 : Bool
  op1 : AluOpType
  value1 : List Float
  expr1 : Index
  reverse1 : Bool
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure TongaReduceMacroSymbolic extends Instruction where
  opcode := "TongaReduceMacroSymbolic"
  op : AluOpType
  is_first_reduce : Bool
  reduce_axes : List LoopAxis
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure CalcVarAddrSymbolic extends Instruction where
  opcode := "CalcVarAddrSymbolic"
  expr_baseoffset : Index
  size : Nat
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure IotaSymbolic extends Instruction where
  opcode := "IotaSymbolic"
  base : Index
  pattern : List APPair
  channel_multiplier : Option Nat := some 0
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

structure TensorScalarAffineSelectSymbolic extends Instruction where
  opcode := "TensorScalarAffineSelectSymbolic"
  base : Index
  pattern : List APPair
  channel_multiplier : Option Nat := some 0
  compare_op : AluOpType
  fill_value : Option Float := some 0
  deriving BEq, Repr, Lean.FromJson, Lean.ToJson

-- Union of all instruction types
inductive Inst where
  | Activation : Activation -> Inst
  | ReadActivationAccumulator : ReadActivationAccumulator -> Inst
  | LoadActFuncSet : LoadActFuncSet -> Inst
  | Memset : Memset -> Inst
  | GetGlobalRankId : GetGlobalRankId -> Inst
  | NoOp : NoOp -> Inst
  | EventSemaphore : EventSemaphore -> Inst
  | AllEngineBarrier : AllEngineBarrier -> Inst
  | Drain : Drain -> Inst
  | Halt : Halt -> Inst
  | Pool : Pool -> Inst
  | Reciprocal : Reciprocal -> Inst
  | Shuffle : Shuffle -> Inst
  | TensorCopy : TensorCopy -> Inst
  | TensorCopyDynamicSrc : TensorCopyDynamicSrc -> Inst
  | TensorCopyDynamicDst : TensorCopyDynamicDst -> Inst
  | IndirectCopy : IndirectCopy -> Inst
  | TensorReduce : TensorReduce -> Inst
  | TensorScalar : TensorScalar -> Inst
  | TensorScalarPtr : TensorScalarPtr -> Inst
  | TensorTensor : TensorTensor -> Inst
  | BNStats : BNStats -> Inst
  | BNStatsAggregate : BNStatsAggregate -> Inst
  | BNGradients : BNGradients -> Inst
  | BNBackprop : BNBackprop -> Inst
  | BNBackprop2 : BNBackprop2 -> Inst
  | StreamShuffle : StreamShuffle -> Inst
  | CalcVarAddr : CalcVarAddr -> Inst
  | StreamTranspose : StreamTranspose -> Inst
  | Select : Select -> Inst
  | CopyPredicated : CopyPredicated -> Inst
  | CustomOp : CustomOp -> Inst
  | BIRKernel : BIRKernel -> Inst
  | NKIKernel : NKIKernel -> Inst
  | GetRandState : GetRandState -> Inst
  | SetRandState : SetRandState -> Inst
  | Rand : Rand -> Inst
  | Iota : Iota -> Inst
  | TensorScalarAffineSelect : TensorScalarAffineSelect -> Inst
  | Dropout : Dropout -> Inst
  | GetCurProcessingRankID : GetCurProcessingRankID -> Inst
  | RegisterAlu : RegisterAlu -> Inst
  | RegisterMove : RegisterMove -> Inst
  | TensorLoad : TensorLoad -> Inst
  | TensorSave : TensorSave -> Inst
  | Call : Call -> Inst
  | SwitchQueueInstance : SwitchQueueInstance -> Inst
  | CoreBarrier : CoreBarrier -> Inst
  | Max : Max -> Inst
  | MaxIndex : MaxIndex -> Inst
  | MatchReplace : MatchReplace -> Inst
  | Gather : Gather -> Inst
  | InlineASMBytes : InlineASMBytes -> Inst
  | Generic : Generic -> Inst
  | GenericCopy : GenericCopy -> Inst
  | GenericRelu : GenericRelu -> Inst
  | AbstractCopy : AbstractCopy -> Inst
  | MatmultBase : MatmultBase -> Inst
  | Matmult : Matmult -> Inst
  | MatmultSparse : MatmultSparse -> Inst
  | DMA : DMA -> Inst
  | Load : Load -> Inst
  | Save : Save -> Inst
  | DMACopy : DMACopy -> Inst
  | ReadVarAddr : ReadVarAddr -> Inst
  | GenericIndirectLoad : GenericIndirectLoad -> Inst
  | IndirectLoad : IndirectLoad -> Inst
  | GenericIndirectSave : GenericIndirectSave -> Inst
  | IndirectSave : IndirectSave -> Inst
  | IndirectSaveAccumulate : IndirectSaveAccumulate -> Inst
  | DMATrigger : DMATrigger -> Inst
  | Collective : Collective -> Inst
  | CollectiveCompute : CollectiveCompute -> Inst
  | CollectiveSend : CollectiveSend -> Inst
  | CollectiveRecv : CollectiveRecv -> Inst
  | DMADescriptor : DMADescriptor -> Inst
  | DMADescriptorCopy : DMADescriptorCopy -> Inst
  | DMADescriptorCCE : DMADescriptorCCE -> Inst
  | DMADescriptorTranspose : DMADescriptorTranspose -> Inst
  | DMADescriptorReplicate : DMADescriptorReplicate -> Inst
  | Terminator : Terminator -> Inst
  | CompareAndBranch : CompareAndBranch -> Inst
  | UnconditionalBranch : UnconditionalBranch -> Inst
  | Return : Return -> Inst
  | Break : Break -> Inst
  | MatmultSymbolic : MatmultSymbolic -> Inst
  | ShuffleSymbolic : ShuffleSymbolic -> Inst
  | TensorScalarSymbolic : TensorScalarSymbolic -> Inst
  | TongaReduceMacroSymbolic : TongaReduceMacroSymbolic -> Inst
  | CalcVarAddrSymbolic : CalcVarAddrSymbolic -> Inst
  | IotaSymbolic : IotaSymbolic -> Inst
  | TensorScalarAffineSelectSymbolic : TensorScalarAffineSelectSymbolic -> Inst
  deriving BEq, Repr

def Inst.toJson : Inst -> Lean.Json
  | Activation x => Lean.toJson x
  | ReadActivationAccumulator x => Lean.toJson x
  | LoadActFuncSet x => Lean.toJson x
  | Memset x => Lean.toJson x
  | GetGlobalRankId x => Lean.toJson x
  | NoOp x => Lean.toJson x
  | EventSemaphore x => Lean.toJson x
  | AllEngineBarrier x => Lean.toJson x
  | Drain x => Lean.toJson x
  | Halt x => Lean.toJson x
  | Pool x => Lean.toJson x
  | Reciprocal x => Lean.toJson x
  | Shuffle x => Lean.toJson x
  | TensorCopy x => Lean.toJson x
  | TensorCopyDynamicSrc x => Lean.toJson x
  | TensorCopyDynamicDst x => Lean.toJson x
  | IndirectCopy x => Lean.toJson x
  | TensorReduce x => Lean.toJson x
  | TensorScalar x => Lean.toJson x
  | TensorScalarPtr x => Lean.toJson x
  | TensorTensor x => Lean.toJson x
  | BNStats x => Lean.toJson x
  | BNStatsAggregate x => Lean.toJson x
  | BNGradients x => Lean.toJson x
  | BNBackprop x => Lean.toJson x
  | BNBackprop2 x => Lean.toJson x
  | StreamShuffle x => Lean.toJson x
  | CalcVarAddr x => Lean.toJson x
  | StreamTranspose x => Lean.toJson x
  | Select x => Lean.toJson x
  | CopyPredicated x => Lean.toJson x
  | CustomOp x => Lean.toJson x
  | BIRKernel x => Lean.toJson x
  | NKIKernel x => Lean.toJson x
  | GetRandState x => Lean.toJson x
  | SetRandState x => Lean.toJson x
  | Rand x => Lean.toJson x
  | Iota x => Lean.toJson x
  | TensorScalarAffineSelect x => Lean.toJson x
  | Dropout x => Lean.toJson x
  | GetCurProcessingRankID x => Lean.toJson x
  | RegisterAlu x => Lean.toJson x
  | RegisterMove x => Lean.toJson x
  | TensorLoad x => Lean.toJson x
  | TensorSave x => Lean.toJson x
  | Call x => Lean.toJson x
  | SwitchQueueInstance x => Lean.toJson x
  | CoreBarrier x => Lean.toJson x
  | Max x => Lean.toJson x
  | MaxIndex x => Lean.toJson x
  | MatchReplace x => Lean.toJson x
  | Gather x => Lean.toJson x
  | InlineASMBytes x => Lean.toJson x
  | Generic x => Lean.toJson x
  | GenericCopy x => Lean.toJson x
  | GenericRelu x => Lean.toJson x
  | AbstractCopy x => Lean.toJson x
  | MatmultBase x => Lean.toJson x
  | Matmult x => Lean.toJson x
  | MatmultSparse x => Lean.toJson x
  | DMA x => Lean.toJson x
  | Load x => Lean.toJson x
  | Save x => Lean.toJson x
  | DMACopy x => Lean.toJson x
  | ReadVarAddr x => Lean.toJson x
  | GenericIndirectLoad x => Lean.toJson x
  | IndirectLoad x => Lean.toJson x
  | GenericIndirectSave x => Lean.toJson x
  | IndirectSave x => Lean.toJson x
  | IndirectSaveAccumulate x => Lean.toJson x
  | DMATrigger x => Lean.toJson x
  | Collective x => Lean.toJson x
  | CollectiveCompute x => Lean.toJson x
  | CollectiveSend x => Lean.toJson x
  | CollectiveRecv x => Lean.toJson x
  | DMADescriptor x => Lean.toJson x
  | DMADescriptorCopy x => Lean.toJson x
  | DMADescriptorCCE x => Lean.toJson x
  | DMADescriptorTranspose x => Lean.toJson x
  | DMADescriptorReplicate x => Lean.toJson x
  | Terminator x => Lean.toJson x
  | CompareAndBranch x => Lean.toJson x
  | UnconditionalBranch x => Lean.toJson x
  | Return x => Lean.toJson x
  | Break x => Lean.toJson x
  | MatmultSymbolic x => Lean.toJson x
  | ShuffleSymbolic x => Lean.toJson x
  | TensorScalarSymbolic x => Lean.toJson x
  | TongaReduceMacroSymbolic x => Lean.toJson x
  | CalcVarAddrSymbolic x => Lean.toJson x
  | IotaSymbolic x => Lean.toJson x
  | TensorScalarAffineSelectSymbolic x => Lean.toJson x

def Inst.fromJson? (j : Lean.Json) : Except String Inst := do
  let name <- j.getObjValAs? String "opcode"
  match name with
  | "Activation" => return .Activation (<- Lean.fromJson? j)
  | "ReadActivationAccumulator" => return .ReadActivationAccumulator (<- Lean.fromJson? j)
  | "LoadActFuncSet" => return .LoadActFuncSet (<- Lean.fromJson? j)
  | "Memset" => return .Memset (<- Lean.fromJson? j)
  | "GetGlobalRankId" => return .GetGlobalRankId (<- Lean.fromJson? j)
  | "NoOp" => return .NoOp (<- Lean.fromJson? j)
  | "EventSemaphore" => return .EventSemaphore (<- Lean.fromJson? j)
  | "AllEngineBarrier" => return .AllEngineBarrier (<- Lean.fromJson? j)
  | "Drain" => return .Drain (<- Lean.fromJson? j)
  | "Halt" => return .Halt (<- Lean.fromJson? j)
  | "Pool" => return .Pool (<- Lean.fromJson? j)
  | "Reciprocal" => return .Reciprocal (<- Lean.fromJson? j)
  | "Shuffle" => return .Shuffle (<- Lean.fromJson? j)
  | "TensorCopy" => return .TensorCopy (<- Lean.fromJson? j)
  | "TensorCopyDynamicSrc" => return .TensorCopyDynamicSrc (<- Lean.fromJson? j)
  | "TensorCopyDynamicDst" => return .TensorCopyDynamicDst (<- Lean.fromJson? j)
  | "IndirectCopy" => return .IndirectCopy (<- Lean.fromJson? j)
  | "TensorReduce" => return .TensorReduce (<- Lean.fromJson? j)
  | "TensorScalar" => return .TensorScalar (<- Lean.fromJson? j)
  | "TensorScalarPtr" => return .TensorScalarPtr (<- Lean.fromJson? j)
  | "TensorTensor" => return .TensorTensor (<- Lean.fromJson? j)
  | "BNStats" => return .BNStats (<- Lean.fromJson? j)
  | "BNStatsAggregate" => return .BNStatsAggregate (<- Lean.fromJson? j)
  | "BNGradients" => return .BNGradients (<- Lean.fromJson? j)
  | "BNBackprop" => return .BNBackprop (<- Lean.fromJson? j)
  | "BNBackprop2" => return .BNBackprop2 (<- Lean.fromJson? j)
  | "StreamShuffle" => return .StreamShuffle (<- Lean.fromJson? j)
  | "CalcVarAddr" => return .CalcVarAddr (<- Lean.fromJson? j)
  | "StreamTranspose" => return .StreamTranspose (<- Lean.fromJson? j)
  | "Select" => return .Select (<- Lean.fromJson? j)
  | "CopyPredicated" => return .CopyPredicated (<- Lean.fromJson? j)
  | "CustomOp" => return .CustomOp (<- Lean.fromJson? j)
  | "BIRKernel" => return .BIRKernel (<- Lean.fromJson? j)
  | "NKIKernel" => return .NKIKernel (<- Lean.fromJson? j)
  | "GetRandState" => return .GetRandState (<- Lean.fromJson? j)
  | "SetRandState" => return .SetRandState (<- Lean.fromJson? j)
  | "Rand" => return .Rand (<- Lean.fromJson? j)
  | "Iota" => return .Iota (<- Lean.fromJson? j)
  | "TensorScalarAffineSelect" => return .TensorScalarAffineSelect (<- Lean.fromJson? j)
  | "Dropout" => return .Dropout (<- Lean.fromJson? j)
  | "GetCurProcessingRankID" => return .GetCurProcessingRankID (<- Lean.fromJson? j)
  | "RegisterAlu" => return .RegisterAlu (<- Lean.fromJson? j)
  | "RegisterMove" => return .RegisterMove (<- Lean.fromJson? j)
  | "TensorLoad" => return .TensorLoad (<- Lean.fromJson? j)
  | "TensorSave" => return .TensorSave (<- Lean.fromJson? j)
  | "Call" => return .Call (<- Lean.fromJson? j)
  | "SwitchQueueInstance" => return .SwitchQueueInstance (<- Lean.fromJson? j)
  | "CoreBarrier" => return .CoreBarrier (<- Lean.fromJson? j)
  | "Max" => return .Max (<- Lean.fromJson? j)
  | "MaxIndex" => return .MaxIndex (<- Lean.fromJson? j)
  | "MatchReplace" => return .MatchReplace (<- Lean.fromJson? j)
  | "Gather" => return .Gather (<- Lean.fromJson? j)
  | "InlineASMBytes" => return .InlineASMBytes (<- Lean.fromJson? j)
  | "Generic" => return .Generic (<- Lean.fromJson? j)
  | "GenericCopy" => return .GenericCopy (<- Lean.fromJson? j)
  | "GenericRelu" => return .GenericRelu (<- Lean.fromJson? j)
  | "AbstractCopy" => return .AbstractCopy (<- Lean.fromJson? j)
  | "MatmultBase" => return .MatmultBase (<- Lean.fromJson? j)
  | "Matmult" => return .Matmult (<- Lean.fromJson? j)
  | "MatmultSparse" => return .MatmultSparse (<- Lean.fromJson? j)
  | "DMA" => return .DMA (<- Lean.fromJson? j)
  | "Load" => return .Load (<- Lean.fromJson? j)
  | "Save" => return .Save (<- Lean.fromJson? j)
  | "DMACopy" => return .DMACopy (<- Lean.fromJson? j)
  | "ReadVarAddr" => return .ReadVarAddr (<- Lean.fromJson? j)
  | "GenericIndirectLoad" => return .GenericIndirectLoad (<- Lean.fromJson? j)
  | "IndirectLoad" => return .IndirectLoad (<- Lean.fromJson? j)
  | "GenericIndirectSave" => return .GenericIndirectSave (<- Lean.fromJson? j)
  | "IndirectSave" => return .IndirectSave (<- Lean.fromJson? j)
  | "IndirectSaveAccumulate" => return .IndirectSaveAccumulate (<- Lean.fromJson? j)
  | "DMATrigger" => return .DMATrigger (<- Lean.fromJson? j)
  | "Collective" => return .Collective (<- Lean.fromJson? j)
  | "CollectiveCompute" => return .CollectiveCompute (<- Lean.fromJson? j)
  | "CollectiveSend" => return .CollectiveSend (<- Lean.fromJson? j)
  | "CollectiveRecv" => return .CollectiveRecv (<- Lean.fromJson? j)
  | "DMADescriptor" => return .DMADescriptor (<- Lean.fromJson? j)
  | "DMADescriptorCopy" => return .DMADescriptorCopy (<- Lean.fromJson? j)
  | "DMADescriptorCCE" => return .DMADescriptorCCE (<- Lean.fromJson? j)
  | "DMADescriptorTranspose" => return .DMADescriptorTranspose (<- Lean.fromJson? j)
  | "DMADescriptorReplicate" => return .DMADescriptorReplicate (<- Lean.fromJson? j)
  | "Terminator" => return .Terminator (<- Lean.fromJson? j)
  | "CompareAndBranch" => return .CompareAndBranch (<- Lean.fromJson? j)
  | "UnconditionalBranch" => return .UnconditionalBranch (<- Lean.fromJson? j)
  | "Return" => return .Return (<- Lean.fromJson? j)
  | "Break" => return .Break (<- Lean.fromJson? j)
  | "MatmultSymbolic" => return .MatmultSymbolic (<- Lean.fromJson? j)
  | "ShuffleSymbolic" => return .ShuffleSymbolic (<- Lean.fromJson? j)
  | "TensorScalarSymbolic" => return .TensorScalarSymbolic (<- Lean.fromJson? j)
  | "TongaReduceMacroSymbolic" => return .TongaReduceMacroSymbolic (<- Lean.fromJson? j)
  | "CalcVarAddrSymbolic" => return .CalcVarAddrSymbolic (<- Lean.fromJson? j)
  | "IotaSymbolic" => return .IotaSymbolic (<- Lean.fromJson? j)
  | "TensorScalarAffineSelectSymbolic" => return .TensorScalarAffineSelectSymbolic (<- Lean.fromJson? j)
  | _ => throw s!"unknown opcode {name}"
